// @concertypin/config/oxlint — Shared base Oxlint ruleset
// Auto-derived from the 6-way intersection of non-Svelte template aggregators.
// Includes cross-template file-pattern exceptions.

/** @import { OxlintConfig } from "oxlint" */

/** @type {OxlintConfig} */
const config = {
    rules: {
        "@typescript-eslint/await-thenable": "error",
        "@typescript-eslint/ban-ts-comment": "warn",
        "@typescript-eslint/no-array-delete": "error",
        "@typescript-eslint/no-base-to-string": "error",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-duplicate-type-constituents": "warn",
        "@typescript-eslint/no-empty-object-type": "warn",
        "@typescript-eslint/no-explicit-any": "warn",
        "@typescript-eslint/no-extra-non-null-assertion": "warn",
        "@typescript-eslint/no-floating-promises": "error",
        "@typescript-eslint/no-for-in-array": "error",
        "@typescript-eslint/no-implied-eval": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-misused-promises": "error",
        "@typescript-eslint/no-namespace": "warn",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-redundant-type-constituents": "warn",
        "@typescript-eslint/no-require-imports": "warn",
        "@typescript-eslint/no-this-alias": "warn",
        "@typescript-eslint/no-unnecessary-type-assertion": "warn",
        "@typescript-eslint/no-unnecessary-type-constraint": "warn",
        "@typescript-eslint/no-unsafe-argument": "error",
        "@typescript-eslint/no-unsafe-assignment": "error",
        "@typescript-eslint/no-unsafe-call": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unsafe-enum-comparison": "error",
        "@typescript-eslint/no-unsafe-function-type": "error",
        "@typescript-eslint/no-unsafe-member-access": "error",
        "@typescript-eslint/no-unsafe-return": "error",
        "@typescript-eslint/no-unsafe-unary-minus": "error",
        "@typescript-eslint/no-wrapper-object-types": "error",
        "@typescript-eslint/only-throw-error": "warn",
        "@typescript-eslint/prefer-as-const": "warn",
        "@typescript-eslint/prefer-namespace-keyword": "warn",
        "@typescript-eslint/prefer-promise-reject-errors": "warn",
        "@typescript-eslint/require-await": "warn",
        "@typescript-eslint/restrict-plus-operands": "error",
        "@typescript-eslint/restrict-template-expressions": "warn",
        "@typescript-eslint/triple-slash-reference": "warn",
        "@typescript-eslint/unbound-method": "error",
        "constructor-super": "off",
        "for-direction": "error",
        "no-array-constructor": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "warn",
        "no-class-assign": "off",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "off",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "warn",
        "no-control-regex": "warn",
        "no-debugger": "warn",
        "no-dupe-class-members": "off",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "off",
        "no-duplicate-case": "error",
        "no-empty": "warn",
        "no-empty-character-class": "error",
        "no-empty-pattern": "warn",
        "no-empty-static-block": "warn",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "warn",
        "no-fallthrough": "warn",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "warn",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "off",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "off",
        "no-prototype-builtins": "warn",
        "no-redeclare": "off",
        "no-regex-spaces": "warn",
        "no-self-assign": "warn",
        "no-setter-return": "off",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "off",
        "no-unassigned-vars": "warn",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": "error",
        "no-unused-expressions": "warn",
        "no-unused-labels": "warn",
        "no-unused-private-class-members": "warn",
        "no-unused-vars": "warn",
        "no-useless-backreference": "error",
        "no-useless-catch": "warn",
        "no-useless-escape": "warn",
        "no-var": "error",
        "prefer-const": "warn",
        "prefer-rest-params": "warn",
        "prefer-spread": "warn",
        "preserve-caught-error": "warn",
        "require-yield": "warn",
        "use-isnan": "error",
        "valid-typeof": "error",
        "@typescript-eslint/no-shadow": "warn",
        eqeqeq: "warn",
        "no-multi-assign": "warn",
        "no-else-return": "warn",
        "no-lonely-if": "warn",
        "no-useless-return": "warn",
        "no-eval": "warn",
        "no-caller": "warn",
        "no-extend-native": "warn",
        "no-extra-bind": "warn",
        "no-proto": "warn",
        "no-sequences": "warn",
        "no-useless-concat": "warn",
        "no-useless-rename": "warn",
        "prefer-template": "warn",
        "object-shorthand": "warn",
    },
    overrides: [
        {
            files: ["**/*.d.ts"],
            rules: {
                "no-unused-vars": "off",
            },
        },
    ],
};

export default config;
